# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'FinanceApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for FinanceApp

  pod 'FacebookCore', '~> 0.8.0'
  pod 'FacebookLogin', '~> 0.8.0'
  pod 'FacebookShare', '~> 0.8.0'

  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Auth', '~> 6.2.0'
  pod 'Firebase/Database', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'
  pod 'Firebase/Storage', '~> 6.2.0'
  pod 'Firebase/Firestore', '~> 6.2.0'

  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.7.1'

  pod 'Charts', '~> 3.3.0'
  pod 'ChameleonFramework', '~> 2.1.0'
  pod 'Eureka', '~> 5.0.0'
  pod 'CleverTap-iOS-SDK'

end
